// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	pokedex "github.com/defryheryanto/pokemon-helper/internal/pokedex"
	pokemon "github.com/defryheryanto/pokemon-helper/internal/pokemon"
	gomock "github.com/golang/mock/gomock"
)

// MockIService is a mock of IService interface.
type MockIService struct {
	ctrl     *gomock.Controller
	recorder *MockIServiceMockRecorder
}

// MockIServiceMockRecorder is the mock recorder for MockIService.
type MockIServiceMockRecorder struct {
	mock *MockIService
}

// NewMockIService creates a new mock instance.
func NewMockIService(ctrl *gomock.Controller) *MockIService {
	mock := &MockIService{ctrl: ctrl}
	mock.recorder = &MockIServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIService) EXPECT() *MockIServiceMockRecorder {
	return m.recorder
}

// GetAllPokedex mocks base method.
func (m *MockIService) GetAllPokedex(ctx context.Context, filter pokedex.GetAllPokedexFilter) ([]pokemon.PokemonData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllPokedex", ctx, filter)
	ret0, _ := ret[0].([]pokemon.PokemonData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllPokedex indicates an expected call of GetAllPokedex.
func (mr *MockIServiceMockRecorder) GetAllPokedex(ctx, filter interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllPokedex", reflect.TypeOf((*MockIService)(nil).GetAllPokedex), ctx, filter)
}

// GetPokedex mocks base method.
func (m *MockIService) GetPokedex(ctx context.Context, pokemonName string) (*pokemon.PokemonData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPokedex", ctx, pokemonName)
	ret0, _ := ret[0].(*pokemon.PokemonData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPokedex indicates an expected call of GetPokedex.
func (mr *MockIServiceMockRecorder) GetPokedex(ctx, pokemonName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPokedex", reflect.TypeOf((*MockIService)(nil).GetPokedex), ctx, pokemonName)
}
