// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	pokemontype "github.com/defryheryanto/pokemon-helper/internal/pokemontype"
	gomock "github.com/golang/mock/gomock"
)

// MockIService is a mock of IService interface.
type MockIService struct {
	ctrl     *gomock.Controller
	recorder *MockIServiceMockRecorder
}

// MockIServiceMockRecorder is the mock recorder for MockIService.
type MockIServiceMockRecorder struct {
	mock *MockIService
}

// NewMockIService creates a new mock instance.
func NewMockIService(ctrl *gomock.Controller) *MockIService {
	mock := &MockIService{ctrl: ctrl}
	mock.recorder = &MockIServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIService) EXPECT() *MockIServiceMockRecorder {
	return m.recorder
}

// CalculateSuggestedType mocks base method.
func (m *MockIService) CalculateSuggestedType(ctx context.Context, uncoveredTypes []pokemontype.IType, suggestLength int) []pokemontype.IType {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CalculateSuggestedType", ctx, uncoveredTypes, suggestLength)
	ret0, _ := ret[0].([]pokemontype.IType)
	return ret0
}

// CalculateSuggestedType indicates an expected call of CalculateSuggestedType.
func (mr *MockIServiceMockRecorder) CalculateSuggestedType(ctx, uncoveredTypes, suggestLength interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CalculateSuggestedType", reflect.TypeOf((*MockIService)(nil).CalculateSuggestedType), ctx, uncoveredTypes, suggestLength)
}

// CalculateTypeCoverage mocks base method.
func (m *MockIService) CalculateTypeCoverage(ctx context.Context, pokemonNames []string) ([]pokemontype.IType, []pokemontype.IType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CalculateTypeCoverage", ctx, pokemonNames)
	ret0, _ := ret[0].([]pokemontype.IType)
	ret1, _ := ret[1].([]pokemontype.IType)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CalculateTypeCoverage indicates an expected call of CalculateTypeCoverage.
func (mr *MockIServiceMockRecorder) CalculateTypeCoverage(ctx, pokemonNames interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CalculateTypeCoverage", reflect.TypeOf((*MockIService)(nil).CalculateTypeCoverage), ctx, pokemonNames)
}
