CREATE TABLE IF NOT EXISTS pokemons (
  id INTEGER PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  name TEXT NOT NULL UNIQUE,
  base_status JSONB NOT NULL,
  types JSONB NOT NULL,
  sprites TEXT NOT NULL
);
